![image.png](attachment:image.png)

### Fala devs, blz?

Temos a honra de apresentar nossa 4ᵃ (quarta) lista de exercícios do Curso de Python 2023 ! 🥳

Dessa vez o tema será o módulo 2, que retrata sobre importações de bibliotecas e sobre a biblioteca _Numpy_ - muito importante para realização de códigos matemáticos e melhora de desempenho das operações.

Esperamos que seja um estudo produtivo e que se divirtam aprendendo!

---
### INSTRUÇÕES:

A realização da lista deve ser feita através do Jupyter Notebook.

Não é obrigatório enviar a lista para fins de certificação na plataforma. No entanto, para os alunos da USP interessados em participar do processo seletivo ou obter créditos AAC (apenas FEANOS), é necessário enviar TODAS as listas.

É altamente recomendado enviar as listas ou, pelo menos, executá-las para praticar todo o conhecimento adquirido durante o curso.

Este DESAFIO foi elaborado para desafiá-lo de verdade. Por isso, não desista de tentar e de continuar com o curso. Ao longo das listas, você perceberá que terá cada vez mais ferramentas para completá-las.

Se surgirem dúvidas sobre a lista, participe das monitorias que serão realizadas às quintas e sábados, das 17h às 18h, no DISCORD. Se o problema não for resolvido, envie uma mensagem para contato.feadev@gmail.com.

O gabarito será disponibilizado na plataforma após o término do período de envio.

---

In [3]:
# Vamos começar importando algumas bibliotecas importantes para os exercícios. ps: Escolham o método que desejarem para resolução.
import math
import numpy as np
import random as rd
import datetime

---
## Questão 0


<h3> Dr. Python </h3>


![gif](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExdnZjMmd5ZzRiOHVka3VkZmlwZXBkNm1lNndyMjU2NzB6ZWxkajV4ciZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/9J7tdYltWyXIY/giphy.gif)

Você foi contratado por uma investidora misteriosa - notavelmente muito rica e influente - para resolver um problema com a internet. Ele está tendo problemas de acesso e percebe que isso é causado por um vírus codificado por uma charada. Sabendo que a única forma de resolver seria acionar um especialista, ela decide te pagar muito dinheiro e a possibilidade de ser contratado por uma grande empresa caso consiga resolver o enigma do vírus.


Segue o texto originado pelo vírus:

#### _"Dois números um, onde há 3 torna-se 5, coloque dois zeros ao fundo, trate de juntar tudo e retorno seu acesso ao WebMundo!"_


<br>

Juntamente ao texto, o vírus fornece o espaço a seguir com alguns algoritmos e arrays para auxiliar na resolução do caso:

In [ ]:
# Algoritmo viral
lista_um = list(np.ones(2))
lista_dois = [3,3]
lista_tres = list(np.zeros(2))

print(lista_um, lista_dois, lista_tres)

[1.0, 1.0] [3, 3] [0.0, 0.0]



Tendo ciência da informação acima descrita, crie um código que _concatene as listas em um array_, lembrando de _alterar os valores_ necessários para _satisfazer a condição_ do vírus ("onde há 3 torna-se 5...")
<br>

In [ ]:
# Seu código começa aqui

lista_dois[1] = 5

total = np.array([lista_um,lista_dois,lista_tres])
total


array([[1., 1.],
       [3., 5.],
       [0., 0.]])

---
## Questão 1

### Cien Tenpo

![gif](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZTZqd3YxNTgyemQyNXE5ODBtYmM5ZTVhbXEwYXZvbzg2YjJoODh4aCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/QBd2kLB5qDmysEXre9/giphy.gif)

Seu amigo acaba de chegar de outro país e se encontra muito confuso com o fuso horário novo e todas as nomenclaturaas. Sabendo do seus conhecimentos em programação, ele decide pedir ajuda para saber a hora com um simples executar de código.

<br>

Pensando nisso, crie um script utilizando a biblioteca _datetime_ que retorne a data atual junto a hora. Armazene em uma variável e exiba com uma mensagem amigável para seu amigo como o exemplo a seguir:

"Olá Cien Tenpo, segue a data e horário em nosso fuso: DATA"

---

###### ps: Caso tenha alguma dúvida com essa biblioteca, pode consultar aqui um exemplo de como usar:

https://www.w3schools.com/python/python_datetime.asp

In [2]:
# Seu código começa aqui

from datetime import datetime
import zoneinfo

agora = datetime.now().strftime('%d/%m/%Y %H:%M')

print("Olá Cien Tenpo, segue a data e horário em nosso fuso: {}".format(agora))

Olá Cien Tenpo, segue a data e horário em nosso fuso: 12/06/2024 20:03


---
## Questão 2

### Sorteando o sorteio

Em um passeio qualquer pela sua cidade, você descobre uma oportunidade incrível de visitar um bingo famoso da cidade em que aquele que sorteia as bolinhas ganha o seu doce preferido como salário. Não querendo perder essa chance, você decide dar uma chance para a vaga e acaba sendo encarregado pela função. Nesse sentido, te passam instruções essenciais para você receber sua recompensa:
- Você deve sortear e exibir cada número no telão
- Após exibir, você deve organizar em ordem crescente os valores no telão
- Ao final, a caixa precisa estar disposta com os valores indo de 1 até 20 em ordem crescente

Segue um código abaixo com os valores a serem sorteados:

In [5]:
# Bolinhas a serem sorteadas

numeros_caixa = list(range(1,21,1))
# 

Sabendo disso, faça um script que _rode todos os números na caixa e sorteie valor a valor_, _exibindo-os no telão_ (printando) e logo em seguida já _organizando em ordem crescente(sort)_:

In [6]:
# Seu código começa aqui

while numeros_caixa:
    numero_aleatorio = rd.choice(numeros_caixa)
    numeros_caixa.remove(numero_aleatorio)
    print("Número retirado: {}".format(numero_aleatorio))
    numeros_caixa.sort()
    print("Números restantes: {}".format(numeros_caixa))
    


Número retirado: 8
Números restantes: [1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
Número retirado: 18
Números restantes: [1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 15, 16, 17, 19, 20]
Número retirado: 1
Números restantes: [2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 15, 16, 17, 19, 20]
Número retirado: 9
Números restantes: [2, 3, 4, 5, 6, 7, 10, 11, 12, 13, 14, 15, 16, 17, 19, 20]
Número retirado: 12
Números restantes: [2, 3, 4, 5, 6, 7, 10, 11, 13, 14, 15, 16, 17, 19, 20]
Número retirado: 14
Números restantes: [2, 3, 4, 5, 6, 7, 10, 11, 13, 15, 16, 17, 19, 20]
Número retirado: 10
Números restantes: [2, 3, 4, 5, 6, 7, 11, 13, 15, 16, 17, 19, 20]
Número retirado: 17
Números restantes: [2, 3, 4, 5, 6, 7, 11, 13, 15, 16, 19, 20]
Número retirado: 5
Números restantes: [2, 3, 4, 6, 7, 11, 13, 15, 16, 19, 20]
Número retirado: 16
Números restantes: [2, 3, 4, 6, 7, 11, 13, 15, 19, 20]
Número retirado: 19
Números restantes: [2, 3, 4, 6, 7, 11, 13, 15, 20]
Número retirado:

---
## Questão 3

### Realizando alguns cálculos
![GIF](https://media.giphy.com/media/21I1WOUDnct4EmSNa6/giphy.gif)

Cansado de viver uma vida de bicos em bingos e resolvendo problemas de pessoas ricas, você opta pela vida estável como contador. Logo que começa em seu emprego seu chefe já te passa uma simples demanda: Somar os arranjos de valores que sejam compatíveis!

<br>

Você como bom dever não vê dificuldade e já parte para resolver o código de imediato utilizando a biblioteca numpy em Python, se deparando com os seguintes arrays transcritos:

In [8]:
# Arranjos
Arranjo_1 = np.array([[1, 2, 3],
                      [4, 5, 6]])

Arranjo_2 = np.array([[13, 14],
                      [15, 16],
                      [17, 18]])

Arranjo_3 = np.array([[7, 8, 9],
                      [10, 11, 12]])

Agora, selecione os arrays que são compatíveis e crie um código simples que realize a soma desses arrays.

In [12]:
# Seu código começa aqui

# Apenas dos compatíveis de início
soma_compativel = Arranjo_1 + Arranjo_3
print("A soma dos arranjos 1 e 3 é: {}".format(soma_compativel))

# Caso de soma dos trÊs
Arranjo_2 = Arranjo_2.reshape((2,3))
soma_todos = Arranjo_1 + Arranjo_2 + Arranjo_3
print("A soma total é {}".format(soma_todos))


A soma dos arranjos 1 e 3 é: [[ 8 10 12]
 [14 16 18]]
A soma total é [[21 24 27]
 [30 33 36]]


## Questão 4
### Mediano
Seu chefe, notando o sucesso no demanda anterior, te passa já uma nova tarefa: Calcular a diferença entre a média dos três arranjos.

---
Seguindo a lógica, use os valores da questão anterior para criar um código que realize o cálculo da diferença entre as médias.

In [18]:
# Seu código começa aqui

Arranjo_1 = np.array([[1, 2, 3],
                      [4, 5, 6]])

Arranjo_2 = np.array([[13, 14],
                      [15, 16],
                      [17, 18]])

Arranjo_3 = np.array([[7, 8, 9],
                      [10, 11, 12]])


media_arranjo_1 = np.mean(Arranjo_1)
media_arranjo_2 = np.mean(Arranjo_2)
media_arranjo_3 = np.mean(Arranjo_3)

print(f"Média Arranjo 1: {media_arranjo_1}")
print(f"Média Arranjo 2: {media_arranjo_2}")
print(f"Média Arranjo 3: {media_arranjo_3}")

# Diferença entre os valores absolutos do arranjo_1 e a média do arranjo_1, e assim, sucessivamente

diferenca_arranjo_1 = Arranjo_1 - media_arranjo_1
print(f"Diferença entre os valores do Arranjo 1 e média de Arranjo 1: {diferenca_arranjo_1}")

diferenca_arranjo_2 = Arranjo_2 - media_arranjo_2
print(f"Diferença entre os valores do Arranjo 2 e média de Arranjo 2: {diferenca_arranjo_2}")

diferenca_arranjo_3 = Arranjo_3 - media_arranjo_3
print(f"Diferença entre os valores do Arranjo 3 e média de Arranjo 3: {diferenca_arranjo_3}")

Média Arranjo 1: 3.5
Média Arranjo 2: 15.5
Média Arranjo 3: 9.5
Diferença entre os valores do Arranjo 1 e média de Arranjo 1: [[-2.5 -1.5 -0.5]
 [ 0.5  1.5  2.5]]
Diferença entre os valores do Arranjo 2 e média de Arranjo 2: [[-2.5 -1.5]
 [-0.5  0.5]
 [ 1.5  2.5]]
Diferença entre os valores do Arranjo 3 e média de Arranjo 3: [[-2.5 -1.5 -0.5]
 [ 0.5  1.5  2.5]]


---
## DESAFIO

### Filtrando (um café matemágico ?)

![gif](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExN3RrbG9uMG53azM4MHhxemtrNzdvbTYxNTA1NzhwaHozeDFnZmI3OCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/OV2uRXy5VIBoPAsH9A/giphy.gif)

Poderia ser um desafio interessante tomar um café matemático?

<br>

A proposta desse desafio é justamente testar essa hipótese !

Temos uma sequência de arranjos que correspondem a "camadas" do café e precisamos ir afunilando e remodelando para que possamos ir somando até formar um único valor (que corresponde ao nosso "café filtrado").

##### PS: alguns grãos estão acima do valor máximo que a cafeteira suporte. Substitua grãos maiores que 50 (gramas) pelo valor 30

In [22]:
# Camadas de grãos de café para serem filtrados. Para fins didáticos imagine que são grãos inteiros e isso não afeta o processo
# Camadas de grãos de café para serem filtrados. Para fins didáticos imagine que são grãos inteiros e isso não afeta o processo
camada_1 = np.array([[5, 2, 7],
                     [12, 5, 9]])

camada_2 = np.array([[15, 8],
                     [4, 10],
                     [52, 65]])

camada_3 = np.array([[17, 11, 19],
                     [6, 22, 26]])

camada_4 = np.array([[78, 15],
                     [16, 23],
                     [12, 32]])

Tendo essas camadas em vista, crie um código que remodele (reshape/resize) os arranjos para uma dimensão comum e possibilite a soma. Ao final printe a soma de todos os valores.

_Lembre-se de corrigir grãos maiores que 50 para um valor 30 (seria uma margem de erro para a máquina)_

In [28]:
# Seu código começa aqui

# Tirando os grãos maiores que 50 e trocando pelo valor 30
ajuste_graos_camada_1 = np.where(camada_1 > 50, 30, camada_1)
print(f"Ajuste dos grãos sobre a camada 1 {ajuste_graos_camada_1}")

ajuste_graos_camada_2 = np.where(camada_2 > 50, 30, camada_2)
print(f"Ajuste dos grãos sobre a camada 2 {ajuste_graos_camada_2}")

ajuste_graos_camada_3 = np.where(camada_3 > 50, 30, camada_3)
print(f"Ajuste dos grãos sobre a camada 3 {ajuste_graos_camada_3}")

# Ajuste das dimensões dos arrays das camadas

camada_1_ajustada = ajuste_graos_camada_1.reshape((1,ajuste_graos_camada_1.size))
camada_2_ajustada = ajuste_graos_camada_2.reshape((1,ajuste_graos_camada_2.size))
camada_3_ajustada = ajuste_graos_camada_3.reshape((1,ajuste_graos_camada_3.size))

# Soma final

resultado_final = np.sum(camada_1_ajustada) + np.sum(camada_2_ajustada) + np.sum(camada_3_ajustada)

print(f"Resultado final: {resultado_final}")




Ajuste dos grãos sobre a camada 1 [[ 5  2  7]
 [12  5  9]]
Ajuste dos grãos sobre a camada 2 [[15  8]
 [ 4 10]
 [30 30]]
Ajuste dos grãos sobre a camada 3 [[17 11 19]
 [ 6 22 26]]
Resultado final: 238
